Updated checks

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,4 +1,13 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npm run build
+echo "Running pre-push checks...🍺"
+
+echo "Building the project🏗️"
+
+npm run build || (
+  echo "Build failed. ❌ "
+  exit 1
+)
+
+echo "Build completed successfully. ✅ "
